name: demucs

channels:
  - pytorch
  - conda-forge

dependencies:
  - python>=3.13.1,<4.0
  - ffmpeg>=4.2
  - pytorch==2.8.0
  - torchaudio==2.8.0
  - tqdm>=4.36
  - pip
  - pip:
    - diffq>=0.2
    - dora-search
    - einops
    - hydra-colorlog>=1.1
    - hydra-core>=1.1
    - julius>=0.2.3
    - lameenc>=1.2
    - openunmix
    - musdb>=0.4.0
    - museval>=0.4.0
    - soundfile
    - submitit
    - treetable>=0.2.3

